name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test PHP Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Run lint
        run: ./vendor/bin/phpcs --standard=PSR12 app/

      - name: Run tests
        run: ./vendor/bin/phpunit

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag PHP Docker image
        run: docker build -t myrepo/php-app:latest .

      - name: Build and tag MySQL Docker image
        run: docker build -t myrepo/mysql:latest ./mysql

      - name: Push PHP Docker image
        run: docker push myrepo/php-app:latest

      - name: Push MySQL Docker image
        run: docker push myrepo/mysql:latest

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to Staging Server
        run: |
          ssh user@staging-server 'docker pull myrepo/php-app:latest && docker pull myrepo/mysql:latest && docker-compose -f /path/to/docker-compose.yml up -d'
