name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test PHP Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      # Restrict phpcs to lint only your PHP files in the root directory
      - name: Run lint
        run: ./vendor/bin/phpcs --standard=PSR12 ./*.php

      - name: Run tests
        run: ./vendor/bin/phpunit
