name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test PHP Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Run lint
        run: ./vendor/bin/phpcs --standard=PSR12 ./*.php

      - name: Run tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to GHCR using Personal Access Token (PAT)
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t deployment-test-php:latest .

      # Tag the Docker image (use lowercase in the repository name)
      - name: Tag Docker image
        run: docker tag deployment-test-php:latest ghcr.io/arshadiqball/deployment-test:latest

      # Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/arshadiqball/deployment-test:latest
